name: notebooks_env

channels:
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults

dependencies:
  - python=3.7
  - ca-certificates=2019.8.28
  - pip
  - pip:
    - ccdproc==2.0.1
    - "-e git+https://github.com/eteq/nbpages.git@b9ec8410803357939210e068af7e14a6f0625fab#egg=nbpages"
    - acstools==3.0.0
    - alabaster==0.7.12
    - appnope==0.1.0
    - astropy==3.2.1
    - astropy-healpix==0.4
    - astroquery==0.3.10
    - astroscrappy==1.0.8
    - attrs==19.1.0
    - Babel==2.7.0
    - backcall==0.1.0
    - beautifulsoup4==4.8.0
    - bleach==3.1.0
    - ccdproc==2.0.1
    - certifi==2019.9.11
    - chardet==3.0.4
    - crds==7.4.1.1
    - cycler==0.10.0
    - Cython==0.29.13
    - decorator==4.4.0
    - defusedxml==0.6.0
    - docutils==0.15.2
    - drizzlepac==2.2.6
    - entrypoints==0.3
    - et-xmlfile==1.0.1
    - filelock==3.0.12
    - fitsblender==0.3.6
    - html5lib==1.0.1
    - idna==2.8
    - imageio==2.5.0
    - imagesize==1.1.0
    - ipykernel==5.1.2
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jdcal==1.4.1
    - jedi==0.15.1
    - Jinja2==2.10.1
    - joblib==0.13.2
    - jsonschema==3.0.2
    - jupyter==1.0.0
    - jupyter-client==5.3.3
    - jupyter-console==6.0.0
    - jupyter-core==4.5.0
    - jwxml==0.3.0
    - keyring==19.2.0
    - kiwisolver==1.1.0
    - lxml==4.4.1
    - MarkupSafe==1.1.1
    - matplotlib==3.1.1
    - mistune==0.8.4
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - -e git+https://github.com/eteq/nbpages.git@b9ec8410803357939210e068af7e14a6f0625fab#egg=nbpages
    - networkx==2.3
    - nictools==1.1.5
    - nose==1.3.7
    - notebook==6.0.1
    - numpy==1.15.4
    - numpydoc==0.9.1
    - openpyxl==2.6.3
    - packaging==19.2
    - pandas==0.25.1
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - photutils==0.7
    - pickleshare==0.7.5
    - Pillow==6.1.0
    - poppy==0.8.0
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - Pygments==2.4.2
    - pyparsing==2.4.2
    - pyregion==2.0
    - pyrsistent==0.15.4
    - pysiaf==0.5.0
    - python-dateutil==2.8.0
    - pytz==2019.2
    - PyWavelets==1.0.3
    - pyzmq==18.1.0
    - qtconsole==4.5.5
    - regions==0.4
    - reproject==0.5.1
    - requests==2.22.0
    - scikit-image==0.15.0
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - Send2Trash==1.5.0
    - six==1.12.0
    - snowballstemmer==1.9.1
    - soupsieve==1.9.3
    - spherical-geometry==1.2.17
    - Sphinx==2.2.0
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - stregion==1.1.6
    - stsci.convolve==2.2.2
    - stsci.image==2.3.3
    - stsci.imagemanip==1.1.4
    - stsci.imagestats==1.6.2
    - stsci.ndimage==0.10.3
    - stsci.skypac==1.0.4
    - stsci.stimage==0.2.4
    - stsci.tools==3.6.0
    - stwcs==1.5.3
    - terminado==0.8.2
    - testpath==0.4.2
    - tornado==6.0.3
    - traitlets==4.3.2
    - urllib3==1.25.6
    - wcwidth==0.1.7
    - webbpsf==0.8.0
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
