name: notebooks_env

channels:
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults

dependencies:
  - python=3.7
  - ca-certificates=2019.8.28
  - pip
  - virtualenv=16.0.0
  - pip:
    - future==0.17.1
    - junitparser==1.3.4
    - '-e git+https://github.com/eteq/nbpages.git@b9ec8410803357939210e068af7e14a6f0625fab#egg=nbpages'
