version: 2.1

executors:
  notebook-executor:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo

jobs:
  Build_Notebooks:
    executor: notebook-executor
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            ./.circleci/setup_env.sh

      - run:
          name: Create Artifacts
          command: |
            python create_artifacts.py

      - store_artifacts:
          path: /tmp/artifacts

      - run:
          name: Build Artifacts
          command: |
            source activate notebooks_env
            python build_artifacts.py

      - store_test_results:
          path: /tmp/test-results

      - run:
          name: Make Pages
          command: |
            source activate notebooks_env
            python make_pages.py

workflows:
  version: 2.1

  build-deploy:
    jobs:
      - Build_Notebooks
