version: 2.1

executors:
  notebook-executor:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo

jobs:
  build_and_check:
    executor: notebook-executor
    steps:

      - checkout

        # - restore_cache:
        # -   keys:
        # -     - v1-env-{{ checksum "environment.yml" }}

      - run:
          name: Setup Environment
          command: |
            ./.circleci/setup_env.sh

        # - save_cache:
        #  key: v1-env-{{ checksum "environment.yml" }}
        #  paths:
        #    - /opt/conda
        #    - src/nbpages

      - run:
          name: Create Artifacts
          command: |
            python create_artifacts.py

      - store_artifacts:
          path: /tmp/artifacts

      - run:
          name: Build Artifacts
          command: |
            python build_artifacts.py

      - store_test_results:
          path: /tmp/build-state.json

workflows:
  version: 2.1

  build-deploy:
    jobs:
      - build_and_check
